# Welcome to Jekyll!
#
# 이 설정 파일은 블로그 전체에 영향을 미치는 설정을 위한 것으로,
# 한 번 설정하고 나서는 거의 수정할 필요가 없는 값들입니다. 이 파일을
# 자주 수정하게 된다면, Jekyll의 데이터 파일 기능을 사용하여
# 자주 업데이트해야 하는 데이터를 관리하는 것을 고려해보세요.
#
# 기술적인 이유로, 'bundle exec jekyll serve'를 사용할 때
# 이 파일은 자동으로 다시 로드되지 *않습니다*. 이 파일을 변경한 경우 서버 프로세스를 다시 시작하세요.
#
# YAML 구문에 도움이 필요하면 다음 참조를 확인하세요:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 사이트 설정
# 이것들은 새 사이트를 개인화하는 데 사용됩니다. HTML 파일을 살펴보면
# {{ site.title }}, {{ site.email }} 등을 통해 접근하는 것을 볼 수 있습니다.
# 원하는 사용자 정의 변수를 만들 수 있으며, 이는 템플릿에서
# {{ site.myvariable }}을 통해 접근할 수 있습니다.

title: 액션 테스트
email: kstost@gmail.com
description: >- # 이것은 "baseurl:"까지 줄바꿈을 무시한다는 의미입니다.
  GitHub Actions 테스트를 위한 저장소입니다. 이 사이트는 GitHub Actions의
  기능을 실험하고 테스트하기 위해 만들어졌습니다.
baseurl: "/actionTest" # 사이트의 하위 경로, 예: /blog
url: "https://kstost.github.io" # 사이트의 기본 호스트 이름 및 프로토콜, 예: http://example.com
twitter_username: kstost
github_username: kstost

# 빌드 설정
theme: minima
plugins:
  - jekyll-feed

# 처리에서 제외
# 기본적으로 다음 항목은 처리되지 않습니다.
# 여기 `exclude:` 키 아래에 나열된 모든 항목은 자동으로
# "기본 목록"에 추가됩니다.
#
# 제외된 항목은 `include:` 목록에 디렉토리나
# 해당 항목의 파일 경로를 명시적으로 나열하여 처리할 수 있습니다.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
